[build]
    command="npm run build"
    publish="/dist"

[build.environment]
    NODE_VERSION = "22"
    NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
