[build]
    command="npm run build"
    publish="dist"

[dev]
    command="npm run dev"

[build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200