[build]
    command="npm run build"
    publish="/fix-my-db-web/dist"

[build.environment]
    NODE_VERSION = "22"
    NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/fix-my-db-web/index.html"
  status = 200
