[build]
    command="npm run build"
    publish="dist"

[build.environment]
    NODE_VERSION = "22"
    NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/fix-my-db-web/*"
  to = "/fix-my-db-web/index.html"
  status = 200